### ISSUE TITLE
Seeing black blocks instead of Ads in Twitter 8.5

### ISSUE THREAD

**Issue by kegobass** [kemmis/iOS-Tweaks#2]
Hi, it looks like the latest Twitter update broke the no ads tweak.  It shows a black block now.  Thanks!
![IMG_DB1309B4C331-1](https://user-images.githubusercontent.com/59669068/72018574-f5665000-3235-11ea-9581-b5e410a4212c.jpeg)

**Comment by kemmis** [comment]
Closed by 04b39fb

**Comment by kemmis** [comment]
I will get this built and deployed soon. Thanks for the PR.
